[INJICERT-585] refactor VC Sign algo impl & add Ed25519Signature2020
mosip/inji-certify pull request #128
Opened 2024-11-05 13:53 UTC by vharsh

2024-11-06 10:20 UTC, vharsh commented on certify-service/src/main/java/io/mosip/certify/services/Ed25519ProofSignature2020.java
> +@Component
I'll add a `DO-NOT-USE` label for this now.

2024-11-06 10:23 UTC, vharsh commented on certify-service/src/test/java/io/mosip/certify/services/KeymanagerLibSignerTest.java
>              Assert.assertNotNull(vcResult.getCredential().getJsonObject().containsKey("proof"));
I removed multiple assert statements as per a good suggested best practice to have one assert per test method.

2024-11-06 10:23 UTC, vharsh commented on certify-service/src/test/resources/application-test.properties
> +mosip.certify.issuer.vc-sign-algo=Ed25519Signature2018
This had to be added because integration tests won't run otherwise.

2024-11-07 07:19 UTC, jainhitesh9998 requested changes

2024-11-07 07:19 UTC, jainhitesh9998 commented on certify-service/src/main/java/io/mosip/certify/services/RsaProofSignature2018.java
> +        return new URDNA2015Canonicalizer();
we'll end up creating new  object every time, can we have a singleton here

2024-11-08 13:05 UTC, jainhitesh9998 approved these changes

2024-11-12 17:40 UTC, vharsh commented
The above build is failing because keymanager [JAR push](https://github.com/mosip/keymanager/pull/324/files) has failed for this PR and DevOps team might have to take a look into this.

2024-11-13 13:57 UTC, jainhitesh9998 approved these changes

2024-11-13 14:42 UTC, merged