[INJICERT-331] Added unit tests for validators and certify issuance service
mosip/inji-certify pull request #165
Opened 2024-12-24 13:34 UTC by Piyush7034

2024-12-24 14:39 UTC, vharsh approved these changes
imo, we should exclude repositories package from the unit test coverage calculation and avoid writing either business logic inside there unless there's a good reason to do so

2024-12-24 14:39 UTC, vharsh commented on certify-service/src/test/java/io/mosip/certify/VCICacheServiceTest.java
> +        when(cacheManager.getCache(VCISSUANCE_CACHE)).thenReturn(cache);
```suggestion
```
nitpick: is this line redundant as this is already added in `setup()` ?

2025-01-06 07:14 UTC, vharsh commented on certify-service/src/test/java/io/mosip/certify/VCICacheServiceTest.java
> +        assertNotNull(result);
```suggestion
```

2025-01-06 07:22 UTC, vharsh commented on certify-service/src/test/java/io/mosip/certify/proof/ProofValidatorFactoryTest.java
> +        ReflectionTestUtils.setField(proofValidatorFactory, "proofValidators", Arrays.asList(jwtProofValidator, anotherProofValidator));
move this to setUp's beforeEach method

2025-01-06 07:26 UTC, vharsh approved these changes
lgtm

2025-01-06 09:16 UTC, Piyush7034 commented on certify-service/src/test/java/io/mosip/certify/VCICacheServiceTest.java
> +        assertNotNull(result);
Removed this line

2025-01-06 09:17 UTC, Piyush7034 commented on certify-service/src/test/java/io/mosip/certify/proof/ProofValidatorFactoryTest.java
> +        ReflectionTestUtils.setField(proofValidatorFactory, "proofValidators", Arrays.asList(jwtProofValidator, anotherProofValidator));
Moved above lines to setUp as it it used multiple times

2025-01-08 13:37 UTC, jainhitesh9998 requested changes

2025-01-08 13:37 UTC, jainhitesh9998 commented on certify-service/src/test/java/io/mosip/certify/proofgenerators/Ed25519Signature2020ProofGeneratorTest.java
> +        when(signatureService.signv2(any(SignRequestDtoV2.class))).thenThrow(new RuntimeException("Signature Failed"));
are we sure the signature service just throws a runtime exception and nothing else? or we are using runtime exception as a catch all?

2025-01-08 13:37 UTC, jainhitesh9998 commented on certify-service/src/test/java/io/mosip/certify/proofgenerators/Ed25519Signature2018ProofGeneratorTest.java
> +        when(signatureService.jwsSign(any(JWSSignatureRequestDto.class))).thenThrow(new RuntimeException("Signature Failed"));
are we sure the signature service just throws a runtime exception and nothing else? or we are using runtime exception as a catch all?

2025-01-08 13:37 UTC, jainhitesh9998 commented on certify-service/src/test/java/io/mosip/certify/proofgenerators/RSASignature2018ProofGeneratorTest.java
> +        assertEquals("Signature Failed", exception.getMessage());
are we sure the signature service just throws a runtime exception and nothing else? or we are using runtime exception as a catch all?

2025-01-08 13:37 UTC, jainhitesh9998 commented on certify-service/src/test/resources/application-test.properties
> +mosip.certify.plugin-mode=DataProvider
how are we testing both data provider and vcissuance mode?

2025-01-08 14:22 UTC, Piyush7034 commented on certify-service/src/test/java/io/mosip/certify/filter/AccessTokenValidationFilterTest.java
> +    private static final String VALID_TOKEN = "header.payload.signature";
Renamed to TOKEN

2025-01-08 14:23 UTC, Piyush7034 commented on certify-service/src/test/java/io/mosip/certify/proofgenerators/Ed25519Signature2018ProofGeneratorTest.java
> +        ArgumentCaptor<JWSSignatureRequestDto> captor = ArgumentCaptor.forClass(JWSSignatureRequestDto.class);
Removed argument captor as it was only used to create a payload with jwsSign method argument capture

2025-01-08 14:25 UTC, Piyush7034 commented on certify-service/src/test/java/io/mosip/certify/proofgenerators/Ed25519Signature2018ProofGeneratorTest.java
> +        when(signatureService.jwsSign(any(JWSSignatureRequestDto.class))).thenThrow(new RuntimeException("Signature Failed"));
Replaced with more specific RequestException that is coming from io.mosip.kernel.signature.exception package and made required changes in the test.

2025-01-08 14:26 UTC, Piyush7034 commented on certify-service/src/test/java/io/mosip/certify/proofgenerators/RSASignature2018ProofGeneratorTest.java
> +        assertEquals("Signature Failed", exception.getMessage());
Replaced with more specific RequestException that is coming from io.mosip.kernel.signature.exception package and made required changes in the test.

2025-01-08 14:27 UTC, Piyush7034 commented on certify-service/src/test/resources/application-test.properties
> +mosip.certify.plugin-mode=DataProvider
We are using different classes for both with a ConditionalOnProperty annotation, so tests for both classes are added with respective conditional property values. Hence both classes are covered

2025-01-09 03:14 UTC, jainhitesh9998 approved these changes

2025-01-09 03:29 UTC, merged