INJICERT-213- Negative testcases
mosip/inji-certify pull request #97
Opened 2024-09-25 14:26 UTC by maheswaras

Added negative test cases for injicertify APIs

2024-10-07 11:05 UTC, mohanachandran-s requested changes

2024-10-07 11:05 UTC, mohanachandran-s commented on apitest/src/main/resources/injicertify/VCIMockIDANegTC/AuthenticateUserForMockIDANegTC/AuthenticateUserForMockIDANegTC.yml
> +	"individualId": "6553455",
Indentation is not correct

2024-10-07 11:05 UTC, mohanachandran-s commented on apitest/src/main/resources/injicertify/VCIMockIDANegTC/GetCredentialForMockIDANegTC/GetCredentialForMockIDANegTC.yml
> +		"type": [{types: "VerifiableCredential"}, {types: "MockVerifiableCredential"}],
Indentation is not correct

2024-10-07 11:05 UTC, mohanachandran-s commented on apitest/src/main/resources/injicertify/VCIMockIDANegTC/GetCredentialForMockIDANegTC/GetCredentialForMockIDANegTC.yml
> +		"proof_type": "jwt"
Indentation is not correct

2024-10-07 11:05 UTC, mohanachandran-s commented on apitest/src/main/resources/injicertify/VCIMockIDANegTC/GetCredentialForMockIDANegTC/GetCredentialForMockIDANegTC.yml
> +		"proof_jwt": "$PROOF_JWT_3$"
Indentation is not correct

2024-10-07 11:05 UTC, mohanachandran-s commented on apitest/src/main/resources/injicertify/VCIMockIDANegTC/GetCredentialForMockIDANegTC/GetCredentialForMockIDANegTC.yml
> +		"proof_jwt": "$PROOF_JWT_3"
Indentation is not correct

2024-10-07 11:05 UTC, mohanachandran-s commented on apitest/src/main/resources/injicertify/VCIMockIDANegTC/GetCredentialForMockIDANegTC/GetCredentialForMockIDANegTC.yml
> +		"proof_jwt": ""
Indentation is not correct

2024-10-07 11:07 UTC, mohanachandran-s requested changes

2024-10-07 11:07 UTC, mohanachandran-s commented on apitest/src/main/resources/injicertify/VCIMockIDANegTC/OAuthDetailsRequestForMockIDANegTC/OAuthDetailsRequestForMockIDANegTC.yml
> +	    "codeChallenge": "$CODECHALLENGE$",
Indentation is not correct

2024-10-08 07:04 UTC, nandhu-kumar approved these changes

2024-10-08 11:30 UTC, mohanachandran-s requested changes

2024-10-08 11:30 UTC, mohanachandran-s commented on apitest/testNgXmlFiles/injicertifyApi.xml
> +		<test name="OAuthDetailsRequestVCIForMockIDANegTC">
Correct the indentation for this line

2024-10-16 04:43 UTC, jainhitesh9998 approved these changes

2024-10-16 04:44 UTC, merged